### ISSUE TITLE
Broken @types/angular

### ISSUE THREAD

**Issue by filipesilva** [DefinitelyTyped/DefinitelyTyped#10082]
Heya,

Currently, `@types/angular` has a dependency on an earlier version of itself as can be seen in https://npmcdn.com/@types/angular@1.5.5-alpha/package.json.

This cause a duplicate definition error when compiling a project that uses it:

```
kamik@T460p MINGW64 /D/sandbox/typescript-types-bug (master)
$ npm run tsc

> typescript-types-bug@1.0.0 tsc D:\sandbox\typescript-types-bug
> tsc

node_modules/@types/angular/index.d.ts(17,21): error TS2300: Duplicate identifier 'angular'.
node_modules/@types/angular/index.d.ts(18,21): error TS2300: Duplicate identifier 'ng'.
node_modules/@types/angular/node_modules/@types/angular/index.d.ts(17,21): error TS2300: Duplicate identifier 'angular'.
node_modules/@types/angular/node_modules/@types/angular/index.d.ts(18,21): error TS2300: Duplicate identifier 'ng'.

(...)
kamik@T460p MINGW64 /D/sandbox/typescript-types-bug (master)
$ npm ls
typescript-types-bug@1.0.0 D:\sandbox\typescript-types-bug
+-- @types/angular@1.5.5-alpha
| +-- UNMET DEPENDENCY @types/angular@1.5.4-alpha
| `-- @types/jquery@1.10.26-alpha
`-- typescript@2.0.0

npm ERR! missing: @types/angular@1.5.4-alpha, required by @types/angular@1.5.5-alpha
```

I've tried looking at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/angular but there is no `package.json` there. Any way I can contribute a fix?

**Comment by joeskeen** [comment]
I noticed this as well (see https://github.com/Microsoft/types-publisher/issues/57)

**Comment by DanielRosenwasser** [comment]
@andy-ms @RyanCavanaugh can you look into this?

**Comment by mhegazy** [comment]
@andy-ms can you take a look at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10086. We should publish the package as well, and make sure we never add a dependency from one package to itself.

**Comment by mhegazy** [comment]
actually never mind, this is not the correct fix. the fix should be done on the publisher side.

**Comment by Lorthirk** [comment]
I also discovered another apparently wrong behavior. I also am about to start a project in TypeScript 2 beta and want to use both @types/angular and @types/angular-ui-router. Problem is, @types/angular-ui-router has a dependency on @types/angular itself (see [](https://npmcdn.com/@types/angular-ui-router@1.1.29-alpha/package.json), thus causing another duplicate definition issue.

On a side note, just tell me whether I should open a separate bug for this.

**Comment by filipesilva** [comment]
@Lorthirk it should be fine as long as the dependency accepts the current version of `@types/angular`, I think. If you get two, it's because it needs another version.

Tbh I'm kinda excited that this is the kinds of bugs we're having, it really shows that typings have made the jump to the current state of the art in dependency management :D

**Comment by andy-ms** [comment]
Fixed by #10086 and Microsoft/types-publisher#63

**Comment by filipesilva** [comment]
@andy-ms awesome! I see there's a release today for `@types/angular` where it's fixed. Cheers!

**Comment by filipesilva** [comment]
@andy-ms @mhegazy after using the newer version, I uncovered another error with `@types/angular`. 

This one is a bit more exotic, and only manifests itself in a very specific case: when having a nested directory with a linked `node_modules`.

I've made a repo where you can test this, here are the repro steps:
```
git clone https://github.com/filipesilva/typescript-types-bug
cd typescript-types-bug
npm install
npm run symlink #in windows this requires admin console
cd folder
npm run tsc
```

Following these steps yields the following message:

```
kamik@T460p MINGW64 /D/sandbox/typescript-types-bug/folder (master)
$ npm run tsc

> typescript-types-bug-nested@ tsc D:\sandbox\typescript-types-bug\folder
> tsc

node_modules/@types/angular/index.d.ts(17,21): error TS2300: Duplicate identifier 'angular'.
node_modules/@types/angular/index.d.ts(18,21): error TS2300: Duplicate identifier 'ng'.
../node_modules/@types/angular/index.d.ts(17,21): error TS2300: Duplicate identifier 'angular'.
../node_modules/@types/angular/index.d.ts(18,21): error TS2300: Duplicate identifier 'ng'.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tsc"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! typescript-types-bug-nested@ tsc: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the typescript-types-bug-nested@ tsc script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the typescript-types-bug-nested package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs typescript-types-bug-nested
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls typescript-types-bug-nested
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\sandbox\typescript-types-bug\folder\npm-debug.log
```

I added in `@types/jasmine` to show that the error is `@types/angular` specific.

To me, the error seems related to these lines: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/angular/index.d.ts#L19-L20

Removing them work, but I am unsure of their need.

**Comment by DanielRosenwasser** [comment]
Can you check one more time @andy-ms?

**Comment by pocesar** [comment]
this is a real blocker, all angular modules are broken atm

**Comment by mhegazy** [comment]
The behavior you are seeing with `npm link` is the same issue as https://github.com/Microsoft/TypeScript/issues/9566. The package depending on itself is fixed in `@types/angular@1.5.7`.

**Comment by mhegazy** [comment]
// cc: @RyanCavanaugh  for Microsoft/TypeScript#9566.

**Comment by filipesilva** [comment]
I should mention that in this case a regular symlink is being used instead of `npm link`, but I understand the end result will be the same as in that issue.

**Comment by filipesilva** [comment]
I tested today with the TS2.0 RC and these were the results:
- with `typescript@2.0.2` (RC) and `@types/angular@1.5.7` I still experience this problem
- with `@types/angular@1.5.13` I do not experience this problem

The underlying cause seems to have been fixed yet, but the Angular 1 types have been updated to avoid this.

**Comment by chrisnicola** [comment]
Currently testing with the same setup above and finding that `angular` is not being added correctly to the global namespace. This was working find before with `typings` though, but now that I'm installing from NPM it is no longer working.

Based on other type definitions like jQuery that have global variables I decided to try declaring a module named "angular" and exporting from that, which seems to fix this, though it isn't that simple. The Gist below shows what I've done

https://gist.github.com/chrisnicola/d0db04d4fc63048f140c81520d2a150c

Am I the only one having this problem? Is there something else I'm doing wrong here?

**Comment by chrisnicola** [comment]
So apparently this is the cause of the issue for me: https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-umd-module-definitions

Some of the files in which I was referencing `angular` globally have `import` or `export` statements in them. Not really excited about this new Typescript "feature", but I suppose I'll have to live with it and go and update about 3 dozen files.

**Comment by filipesilva** [comment]
Ran into this again today, specifically the problem with symlinks. My setup is something like this:
```
node_modules/
folder
  another_folder
    node_modules/ (symlinked to ../../node_modules)
    app/ (angular1 app in typescript)
    tsconfig.json
    (other build files)
````
If I just have `@types/angular`, `tsc` runs fine. If I have the whole suite (`@types/angular-{animate,cookies,mocks,resource,route,sanitize}`) then I start getting loads of type errors:
```
$ npm run tsc

> angular-examples@1.0.0 tsc D:\work\angular.io\public\docs\_examples\upgrade-phonecat-1-typescript\ts
> tsc

../../node_modules/@types/angular/index.d.ts(17,21): error TS2300: Duplicate identifier 'angular'.
../../node_modules/@types/angular/index.d.ts(18,21): error TS2300: Duplicate identifier 'ng'.
app/app.animations.ts(5,3): error TS2339: Property 'animation' does not exist on type 'IModule'.
app/app.config.ts(6,45): error TS2305: Module 'angular' has no exported member 'route'.
app/core/checkmark/checkmark.filter.spec.ts(5,22): error TS2339: Property 'mock' does not exist on type 'IAngularStatic'.
app/core/phone/phone.service.spec.ts(18,22): error TS2339: Property 'mock' does not exist on type 'IAngularStatic'.
app/core/phone/phone.service.spec.ts(23,18): error TS2339: Property 'expectGET' does not exist on type 'IHttpBackendService'.
app/core/phone/phone.service.spec.ts(30,18): error TS2339: Property 'verifyNoOutstandingExpectation' does not exist on type 'IHttpBackendService'.
app/core/phone/phone.service.spec.ts(31,18): error TS2339: Property 'verifyNoOutstandingRequest' does not exist on type 'IHttpBackendService'.
app/core/phone/phone.service.spec.ts(39,18): error TS2339: Property 'flush' does not exist on type 'IHttpBackendService'.
app/core/phone/phone.service.ts(5,33): error TS2305: Module 'angular' has no exported member 'resource'.
app/phone-detail/phone-detail.component.spec.ts(5,22): error TS2339: Property 'mock' does not exist on type 'IAngularStatic'.
app/phone-detail/phone-detail.component.spec.ts(18,46): error TS2305: Module 'angular' has no exported member 'route'.
app/phone-detail/phone-detail.component.spec.ts(20,20): error TS2339: Property 'expectGET' does not exist on type 'IHttpBackendService'.
app/phone-detail/phone-detail.component.spec.ts(32,20): error TS2339: Property 'flush' does not exist on type 'IHttpBackendService'.
app/phone-detail/phone-detail.component.ts(7,37): error TS2305: Module 'angular' has no exported member 'route'.
app/phone-list/phone-list.component.spec.ts(6,22): error TS2339: Property 'mock' does not exist on type 'IAngularStatic'.
app/phone-list/phone-list.component.spec.ts(15,20): error TS2339: Property 'expectGET' does not exist on type 'IHttpBackendService'.
app/phone-list/phone-list.component.spec.ts(26,20): error TS2339: Property 'flush' does not exist on type 'IHttpBackendService'.
node_modules/@types/angular-resource/index.d.ts(192,40): error TS2305: Module 'angular' has no exported member 'resource'.
node_modules/@types/angular/index.d.ts(17,21): error TS2300: Duplicate identifier 'angular'.
node_modules/@types/angular/index.d.ts(18,21): error TS2300: Duplicate identifier 'ng'.
```

I fixed it by adding the base `../../node_modules/@types` as `typeRoots` to my `tsconfig.json`:
```
    "typeRoots": [
      "../../node_modules/@types/"
    ]
```

I tried adding the local `node_modules/@types`, but that did not work.

**Comment by mhegazy** [comment]
@filipesilva this issue is the same as https://github.com/Microsoft/TypeScript/issues/9091

**Comment by filipesilva** [comment]
@mhegazy thank you for the ref, I'll transfer my comment there.

**Comment by adityaJajpure** [comment]
D:\Learning_Stuff\Angular Js\Angular7>npm install -g @angular/cli
npm ERR! Unexpected end of JSON input while parsing near '...e":"latest","@types
/q'

How to resolve it?
