### ISSUE TITLE
lodash: Type of "key" in NumericDictionaryIterator is incorrect at runtime

### ISSUE THREAD

**Issue by UselessPickles** [DefinitelyTyped/DefinitelyTyped#23723]
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @kuzn-ilya @stepancar @ericanderson @aj-r @Ailrun @e-cloud @jtmthf 

The `NumericDictionaryIterator`'s `key` param is incorrectly typed compared to runtime values. The type of `key` is `number` (makes sense, since it's a Dictionary keyed by `number`), but at runtime, keys of objects are always `string`. 

I encountered this while using `_.map()` on a `NumericDictionary`. At runtime, `key` is a string and was creating incorrect data (because I expect it to be a number). I couldn't use `parseInt()` to convert it to a number, because `parseInt()` only accepts `string`, but `key` is typed as `number` at compile time.

To get correct behavior, I needed to use `parseInt(key as any, 10)` to convert the run time string value to a number at run time.

I didn't want to make a sweeping change like this in a PR, because I'm not aware of intricacies where the current definition of `NumericDictionaryIterator` may actually be correct at run time. Is the fix really as simple as replacing all current usages of `NumericDictionaryIterator` (and related) types with the corresponding `DictionaryIterator` (and related) types, and deleting the `NumericDictionaryIterator` (and related) types? It seems that the various overloads of methods like `_.map()` that accept a `NumericDictionary` should use a plain `DictionaryIterator`.

If someone can confirm that the fix is that simple, I'd be willing to make the changes.

**Comment by UselessPickles** [comment]
So I tried simply changing the definition of NumericDictionaryIterator's `key` param to type `string`. After updating the various numericDictionaryIterator vars in the unit tests to similarly define their `key` param to type `string`, I'm getting several errors in the unit tests where a numericDictionary and numericDictionaryIterator are passed to various lodash methods because none of the overload signatures are being selected (defaults to the last most generic signature).

**Comment by aj-r** [comment]
Can you push your code to github and give me a link to it? I'll see if I can figure out what's up.

**Comment by UselessPickles** [comment]
Will do later tonight.

**Comment by UselessPickles** [comment]
@aj-r Here's the branch with my changes pushed: https://github.com/UselessPickles/DefinitelyTyped/tree/lodash_numeric_dictionary_iterator

One of the two places that `NumericDictionaryIterator` is defined also incorrectly specified the 3rd param as type `Dictionary` instead of `NumericDictionary`. I fixed this, but then started wondering which is actually more correct? 

Should the type of the 3rd param match the compile-time type of the object, or should it be compatible with the type of the `key` passed in to the iterator? It's technically possible at run-time to iterate over additional keys on the object that are not numeric, so maybe it's not safe to assume that all possible keys passed to the iterator could be parsed into integers to be used as keys to a `NumericDictionary`.

Also noteworthy is that the unit tests (via `npm run lint lodash`) failed with the following error BEFORE I made any changes:
```
Error: D:/DevProjects/github/DefinitelyTyped/types/lodash/lodash-tests.ts:8120:38
ERROR: 8120:38  expect  TypeScript@next compile error:
Argument of type '{ foo: (v: string) => boolean; }' is not assignable to parameter of type 'ConformsPredicateObject<{ foo: any; }>'.
  Types of property 'foo' are incompatible.
    Type '(v: string) => boolean' is not assignable to type '((val: {}) => boolean) | undefined'.
      Type '(v: string) => boolean' is not assignable to type '(val: {}) => boolean'.
        Types of parameters 'v' and 'val' are incompatible.
          Type '{}' is not assignable to type 'string'.
```

Thanks for looking!

**Comment by aj-r** [comment]
I think the 3rd parameter should still be a `NumericDictionary`. It's the same as the source object, so it should have the same type. The downside is, now you can't do this:

```ts
(value: any, key: string, collection: NumericDictionary<any>) => {
    collection[key];
}
```

However that's kind of a strange thing to do anyway - you should just use `value` instead.

I'll clone your code and see what's up with the errors.

**Comment by aj-r** [comment]
Looks like you forgot to update a couple of iterators (in `flatMapDeep` and `flatMapDepth`). I fixed those and I'm not getting errors anymore. At least in VS Code... `npm run lint lodash` doesn't work because it gives me this error:

```
Error: Since this type definition includes a header (a comment starting with `// Type definitions for`), assumed this was a DefinitelyTyped package.
But it is not in a `DefinitelyTyped/types/xxx` directory.
```

Which is weird because it definitely is in a `DefinitelyTyped/types/xxx` directory.

**Comment by UselessPickles** [comment]
Oh, wow. How did I miss those? Thanks for looking. After making those changes, VS Code reports 0 errors, and executing `npm run lint lodash` (from the `DefinitelyTyped` root directory) reports only the one error that it reported before I made any changes.

PR coming soon...

**Comment by UselessPickles** [comment]
It's going to take some more work before I create a PR, because I just discovered that several lodash methods are not yet overloaded to handle params of type `NumericDictionary<T>` and `NumericDictionaryIterator<T>`. So when trying to test my changes, it was using the overload for `Dictionary<T>` even though I was passing a `NumericDictionary`, and the `value` param to my iterator was always type `{}` instead of the correct type. 

I'll work on fixing those.

**Comment by UselessPickles** [comment]
@aj-r  While going through to add support for `NumericDictionary` and `NumericDictionaryIterator` to all methods that are missing it, I've come across a few inconsistencies that I'm hoping you can explain:

* Some methods are specifically overloaded to handle collections of both `Array<T>` and `List<T>`, while others only support one or the other. Is there some method to this madness, or should pretty much all lodash methods support both?
* If a method supports a collection of type `List<T>`, is there even any reason to overload it to also support `Array<T>`? 
* Methods of `ImplicitObjectWrapper` and `ExplicitObjectWrapper` support iterators of both types `ListIterator` and `DictionaryIterator`. Why? Should they really only support `DictionaryIterator` (and now `NumericDictionaryIterator`)?
* To properly support the distinction between `Dictionary` and `NumericDictionary`, should there also be `Implicit/ExplicitDictionaryWrapper` and `Implicit/ExplicitNumericDictionaryWrapper` with corresponding `LodashStatic` method signature overloads?
```ts
    interface LoDashStatic {
        (value: number): LoDashImplicitWrapper<number>;
        (value: string): LoDashImplicitStringWrapper;
        (value: boolean): LoDashImplicitWrapper<boolean>;
        (value: Array<number>): LoDashImplicitNumberArrayWrapper;
        <T>(value: Array<T>): LoDashImplicitArrayWrapper<T>;
        <T>(value: Dictionary<T>): LoDashImplicitDictionaryWrapper<T>;
        <T>(value: NumericDictionary<T>): LoDashImplicitNumericDictionaryWrapper<T>;
        // default to less specific "LoDashImplicitObjectWrapper" only if "value" is not specifically
        // a Dictionary or NumericDictionary (would this only happen if it has both number and string indexes)?
        // is this even necessary?
        <T extends {}>(value: T): LoDashImplicitObjectWrapper<T>;
        (value: any): LoDashImplicitWrapper<any>;
    }
```

**Comment by UselessPickles** [comment]
And I just now realized that there are essentially two completely different versions of types for lodash (for lodash 3 and lodash 4), and I'm not sure if I should be trying to update both or not. Suddenly starting to feel like I'm way in over my head with this.

**Comment by aj-r** [comment]
@UselessPickles to answer your other questions:

> Some methods are specifically overloaded to handle collections of both `Array<T>` and `List<T>`, while others only support one or the other. Is there some method to this madness, or should pretty much all lodash methods support both?

In general the `Array<T>` overloads are redundant. Without the array overloads, the `collection` parameter will have type `List<T>` instead of `Array<T>`, but I don't think that's a big deal. There are some cases where the array overloads are necessary, though - the ones that affect the return type, like `forEach`.

> If a method supports a collection of type `List<T>`, is there even any reason to overload it to also support `Array<T>`?

In general, no. See above.

> Methods of `ImplicitObjectWrapper` and `ExplicitObjectWrapper` support iterators of both types `ListIterator` and `DictionaryIterator`. Why? Should they really only support `DictionaryIterator` (and now `NumericDictionaryIterator`)?

They should support both `DictionaryIterator` and `ListIterator`. The implicit/explicit wrappers can wrap any type (including arrays, object, and primitives). In general, the wrapper overloads should mirror the corresponding overloads in `LoDashStatic`.

Unless you're looking at an old version of lodash? In which case `List<T>` got wrapped using `LoDashImplicitObjectWrapper`. But that is no longer the case.

> To properly support the distinction between Dictionary and `NumericDictionary`, should there also be Implicit/ExplicitDictionaryWrapper and Implicit/ExplicitNumericDictionaryWrapper with corresponding `LodashStatic` method signature overloads?

Hmm... what version of lodash are you looking at? There should only be 2 main wrapper types now - `LoDashImplicitWrapper` and `LoDashExplicitWrapper`. The more specific types (`LodashImplicitArrayWrapper`, `LoDashImplicitObjectWrapper`, etc.) are just type aliases, and are only kept for backwards compatibility reasons. We should not add special types for numeric dictionary wrappers.

**Comment by aj-r** [comment]
@UselessPickles Actually, now that the `key` parameter has type `string`, most of the `NumericDictionary` overloads are completely redundant and should be removed. They'll fall back to the `T extends object` overload instead, which is exactly what we want.

I think this would be a good rule: if there's a `T extends object` overload, but NO `Dictionary<T>` overload, then there shouldn't be a `NumericDictionary<T>` overload, either. However if a `Dictionary<T>` exists, then leave the `NumericDictionary<T>` overload, too.

**Comment by UselessPickles** [comment]
I think I’ve been looking mostly at the v3 code so far, so that could explain some of the confusion. I’ll focus on non-v3 files now. 

Just to confirm... is v4 everything in the root Lodash folder AND the common folder?

**Comment by aj-r** [comment]
Yes

**Comment by UselessPickles** [comment]
@aj-r I'm still slowly picking away at this, but have run into some difficulties.

Typescript does not seem to seem to treat index signatures with different key types (number vs string) as different for the purpose of assignability. A `Dictionary` is assignable to a `NumericDictionary` and vice versa. Due to this, it's impossibel to select a different signature overload based on a param beign either `Dictionary` or `NumericDictionary`.

This is not an issue for most methods (like `forEach`, `map`, etc.) because they can mostly be implemented in terms of `T extends object` and `ObjectIterator<T>`.

But methods like `omit` and `mapValues` really should either return a `Dictionary`  or a `NumericDictionary` dependign on the param type. As far as i can tell, this is currently impossible, so we have to live with it always returning a `Dictionary`, even if the param is `NumericDictionary`.

Here's a typescript playground link where I demonstrate the issue (hover over "result1" and "result2" too see their types): https://www.typescriptlang.org/play/#src=type%20Dictionary%3CT%3E%20%3D%20%7B%20%5Bkey%3A%20string%5D%3A%20T%20%7D%3B%0D%0Atype%20NumericDictionary%3CT%3E%20%3D%20%7B%20%5Bkey%3A%20number%5D%3A%20T%20%7D%3B%0D%0A%0D%0Adeclare%20function%20omit%3CT%3E(obj%3A%20Dictionary%3CT%3E%2C%20propName%3A%20string)%3A%20Dictionary%3CT%3E%3B%0D%0Adeclare%20function%20omit%3CT%3E(obj%3A%20NumericDictionary%3CT%3E%2C%20propName%3A%20string)%3A%20Dictionary%3CT%3E%3B%0D%0A%0D%0Adeclare%20let%20dict%3A%20Dictionary%3Cnumber%3E%3B%0D%0Adeclare%20let%20numericDict%3A%20NumericDictionary%3Cnumber%3E%3B%0D%0A%0D%0A%2F%2F%20index%20key%20type%20doesn't%20affect%20assignability%3F%0D%0Adict%20%3D%20numericDict%3B%0D%0AnumericDict%20%3D%20dict%3B%0D%0A%0D%0Aconst%20result1%20%3D%20omit(dict%2C%20%22blah%22)%3B%0D%0A%2F%2F%20Type%20of%20%22result2%22%20is%20Dictionary%3Cnumber%3E%20instead%20of%20NumericDictionary%3Cnumber%3E!%0D%0Aconst%20result2%20%3D%20omit(numericDict%2C%20%22blah%22)%3B%0D%0A%0D%0A

Does this look like a TypeScript bug to you?

**Comment by UselessPickles** [comment]
BTW - I have pushed all my changes so far: https://github.com/UselessPickles/DefinitelyTyped/tree/lodash_numeric_dictionary_iterator

I think I'm about ready to create a PR, pending discussion of the issue in my previous comment.

**Comment by aj-r** [comment]
@UselessPickles  Some thoughts:

Returning `Dictionary<T>` is still technically correct for `omit`, since you can access properties using `obj["0"]`. But that's not ideal since you are probably using `NumericDictionary` because you want to access properties using `obj[0]`. On the other hand, though, `omit` has never supported `NumericDictionary`, so we could live with this since we're not breaking anything.

Similar story with `mapValues`.

To overcome this, we could try adding a new dictionary type like this, and use it as the return type when needed:

```ts
interface GeneralDictionary<T> {
    [index: string | number]: T;
}
```

I'm not sure if that works or if it will break things. If it breaks, I say live without `NumericDictionary` support on those functions, since we never supported `NumericDictionary` in the first place. Worst case, since `Dictionary` and `NumericDictionary` are assignable to each other, you can do this: `const omitted: NumericDictionary<string> = _.omit(obj, 1);`

**Comment by UselessPickles** [comment]
Since `NumericDictionary` is assignable to `Dictionary`, it's impossible to explicitly not support `NumericDictionary`. We can only acknowledge that the types at compile time will be incorrect if `NumericDictionary` is used.

I'll play around with the `GeneralDictionary` idea and see if it makes anything better.

I'll also file an issue on the TypeScript github project about this. It sure seems to me that the key type of the index signature should be taken into consideration when determining assignability.

**Comment by aj-r** [comment]
@UselessPickles looks like `[index: string | number]: T;` doesn't work. You could try this though:

```ts
interface GeneralDictionary<T> {
    [index: string]: T;
    [index: number]: T;
}
```

... and return that type as necessary for `mapValues`. That way, in the result, people can access properties via string or number.

I have a few minor ideas for improvement, too. They're easier to explain as PR comments, so go ahead and submit your PR when ready, and I'll comment on it.

**Comment by UselessPickles** [comment]
Getting closer to a PR. I got `_.omit` fully working properly with both `Dictionary` and `NumericDictionary` (see this comment: https://github.com/Microsoft/TypeScript/issues/22233#issuecomment-369788860)

I'm now fixing up some overloads for `_.mapValues` to work "good enough" so that it works perfectly for `Dictionary` and works "acceptably" for `NumericDictionary` by returning a `Dictionary` of the correct value type.

I'm adding tons of unit tests for `mapValues` now. Maybe I'll be ready for a PR tomorrow night.

**Comment by UselessPickles** [comment]
@aj-r There's an overload of `mapValues`:

```ts
        mapValues<T extends object>(obj: T | null | undefined): T | {};
```

The `| {}` part makes the result pretty much useless. I think it would make more sense as:

```ts
        mapValues<T extends object>(obj: T | null | undefined): Partial<T>;
```

So that you can still attempt to access all properties of the object's type, but the values amy all be undefined if `null` or `undefined` was provided as the param value.

What do you think?

There were actually no unit tests for `mapValues` at all, and adding unit tests is uncovering quite a few flaws with the signatures, the order of the overloads, etc.

**Comment by aj-r** [comment]
@UselessPickles I'm not a huge fan of `Partial<T>` since it doesn't seem quite right in this situation. But I agree that it's probably more useful than `T | {}` so go ahead.

**Comment by UselessPickles** [comment]
Keep in mind that there is also an override like this:
```ts
    mapValues<T extends object>(obj: T): T;
```

So you'll only get the `Partial<T>` result if the param is possibly null/undefined. I can't think of anything that is more fitting or more technically accurate than `Partial<T>` for that situation.
