### ISSUE TITLE
Error: node_modules/@types/jasmine/index.d.ts(138,47): error TS1005: ';' expected.

### ISSUE THREAD

**Issue by stefdelec** [DefinitelyTyped/DefinitelyTyped#30310]
If you know how to fix the issue, make a pull request instead.

- [ I tried using the `@types/jamine` package and had problems( 2.8.11)
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/index.d.ts

I have the following errors 
```
Error: node_modules/@types/jasmine/index.d.ts(138,47): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(138,90): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(138,104): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(138,112): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,113): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,121): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(138,147): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(138,162): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(138,163): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,164): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,165): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,179): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,183): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,208): error TS1005: '{' expected.
node_modules/@types/jasmine/index.d.ts(138,217): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,222): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,227): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,228): error TS1109: Expression expected.
node_modules/@types/jasmine/index.d.ts(138,230): error TS1005: ')' expected.
```

@armanio123

**Comment by burtek** [comment]
@stefdelec Which typescript version are you using?

**Comment by stefdelec** [comment]
typescript@2.6.2

**Comment by burtek** [comment]
Not really. The package itself [says it's for TS 2.8+](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/index.d.ts#L11), and the syntax used in line `138` has been introduced first in TS 2.7 (i.e. [Constant-named properties](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html))

**Comment by thinkdifferentwebsite** [comment]
I am also having same issue.But when i am trying to use higher version of typescript its throwing some other error.

**Comment by burtek** [comment]
@saurabhsharmaui which TS version exactly and what kind of error?

**Comment by saurabhsharmaui** [comment]
Currently i am using "typescript": "~2.3.4", and "@types/jasmine": "~2.8.1", and with this combination i am getting above error,but same thing was working fine till yesterday.
Now as per your comment i tried using higher version it got failed in npm install.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

npm WARN optional Skipping failed optional dependency /live-server/chokidar/fsevents:

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:

npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

npm WARN ng2-select@1.2.0 requires a peer of @angular/common@^2.3.0 but none was installed.

npm WARN ng2-select@1.2.0 requires a peer of @angular/core@^2.3.0 but none was installed.

npm WARN @angular/core@4.4.7 requires a peer of zone.js@^0.8.4 but none was installed.

npm ERR! Linux 4.4.121-92.85-default

npm ERR! argv "/opt/JE2A1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS6.5.0/bin/node" "/opt/JE2A1/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS6.5.0/bin/npm" "install"

npm ERR! node v6.5.0

npm ERR! npm  v3.10.3

npm ERR! path /home/je2adm/.npm/content-type/1.0.4/package.tgz.1017518879

npm ERR! code ENOENT

npm ERR! errno -2

npm ERR! syscall rename



npm ERR! enoent ENOENT: no such file or directory, rename '/home/je2adm/.npm/content-type/1.0.4/package.tgz.1017518879' -> '/home/je2adm/.npm/content-type/1.0.4/package.tgz'

npm ERR! enoent ENOENT: no such file or directory, rename '/home/je2adm/.npm/content-type/1.0.4/package.tgz.1017518879' -> '/home/je2adm/.npm/content-type/1.0.4/package.tgz'

npm ERR! enoent This is most likely not a problem with npm itself

npm ERR! enoent and is related to npm not being able to find a file.

npm ERR! enoent

**Comment by burtek** [comment]
Looks like problem with jenkins' installation of npm, similar problems have been reported previously (i.e. [here](https://github.com/mapbox/node-sqlite3/issues/866) or [here](https://github.com/mapbox/node-sqlite3/issues/900)) and it might not be directly connected to typescript. One of suggested fixes was to completely reinstall npm.

Are you installing TS globally or locally for your project? Have you tried removing `node_modules` and `package-lock.json`, clearing npm cache (`npm cache clean --force`) and reinstalling dependencies?

**Comment by saurabhsharmaui** [comment]
Hi @burtek Thanks you very much for your support.I check version history i see they have updated to newer version yesterday because of that changes it was getting failed i went back and changed to 2.8.9 its working fine.

**Comment by burtek** [comment]
@saurabhsharmaui glad I could help

**Comment by vnazarchukmob** [comment]
Hi. I have same issue. typescript: 2.9.2 and @types/jasmine: 2.8.9. Have no idea how to fix it. Tried all above, nothing help

**Comment by mowgliLab** [comment]
I have the same error at work.
I am working on a generated template for base project. So a brand new project is breaking today but dit not yesterday.

Extract of my package.json
```
...
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.6.8",
        "@angular/cli": "~6.0.8",
        "@angular/compiler-cli": "^6.0.3",
        "@angular/language-service": "^6.0.3",
        "@types/jasmine": "~2.8.6",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
...
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "^3.0.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.0",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
...
        "ts-node": "~5.0.1",
        "tslint": "~5.9.1",
        "typescript": "~2.7.2"
    },
...
```

**Comment by burtek** [comment]
@mowgliLab as I mentioned above, `@types/jasmine` is for TS 2.8+, while you're still using TS 2.7.x. Upgrade `typescript` to at least `2.8.0`.

**Comment by burtek** [comment]
@mowgliLab The problem is, the current version `2.8.11` which requires TS 2.8 satisfies your semver of `~2.8.6`, so while it might be working for old projects, creating new ones would use version 2.8.11 incompatible with TS 2.7.2. You should update the template you use to use TS of at least 2.8.x branch

**Comment by vnazarchukmob** [comment]
@burtek yes, it was installed globally with lower version 2.3.4. I upgraded it to 3.1.6. but it doesn't help

**Comment by burtek** [comment]
@vnazarchukmob just to be sure: You have globally installed TS 3.1.6, locally installed TS 2.9.2, locally installed @types/jasmine of 2.8.9 and you're getting the error from first post. Is that correct?

**Comment by mowgliLab** [comment]
Ok, I will check if it's ok tu upgrade for new projects.
I've tested with typescript 3.1.6 and it works.

Thank you @burtek

**Comment by burtek** [comment]
@mowgliLab glad I could help

**Comment by burtek** [comment]
Last thing that comes to my mind is to reinstall `node_modules`, but I don't think that's gonna help. I'm out of ideas 😢

@armanio123, do you have any idea?

**Comment by r3hxn** [comment]
same issue , started yesterday.

**Comment by burtek** [comment]
@r3hxn Did you read the conversations? Please make sure you're using TS of at least 2.8

**Comment by r3hxn** [comment]
> @r3hxn Did you read the conversation? Please make sure you're using TS of at least 2.8

thanks , am working through it, the problem seems to only appear on our Jenkins pipeline

**Comment by saurabhsharmaui** [comment]
@r3hxn if you don't want to change typescript version just change @type/jasmine version to 2.8.9.It will work fine. Here problem is with new release of @type/jasmine which needs higher version of typescript.

**Comment by r3hxn** [comment]
thanks @saurabhsharmaui that helps

**Comment by saurabhsharmaui** [comment]
@r3hxn glad I could help.

**Comment by jakubjosef** [comment]
I had the same issue, upgrading typescript to latest helps.
The problem is Angular 6 using TS 2.7.2 AFAIK, so all new apps created by `ng new` from version ~6.0.0 will have this issue.

**Comment by zezke** [comment]
> 
> 
> > @r3hxn Did you read the conversation? Please make sure you're using TS of at least 2.8
> 
> thanks , am working through it, the problem seems to only appear on our Jenkins pipeline

We're experiencing the very same thing: works on the dev machines, but not on Jenkins.

**Comment by pnaika** [comment]
@types/jasmine as 2.8.8 and typescript to 2.6.2 worked for me

**Comment by hudzenko** [comment]
"@types/jasmine": "2.8.3" with the same typescript as it was before did the trick for me.

**Comment by nabidul** [comment]
"@types/jasmine": "2.8.6" & "typescript": "2.7.2"  worked.
The problem is "@types/jasmine": "~2.8.6" - > update to 2.8.11 incompatible with typescript to 2.7.2(require 3.+)

**Comment by srivasthava** [comment]
After updating "typescript": "^3.1.6" and  "@types/jasmine": "^2.8.11" Builds succeeded in tfs build servers

**Comment by schippie** [comment]
We also ran into this issue, and I have to say that relying on a new typescript version should be considered a breaking change meaning the package version (according to semver) should have been bumped to 3.X.X instead of the patch version it received. This causes a lot of issues for people which could have been avoided making it an inexcusable error.

**Comment by HarshitChhipa** [comment]
we are having the same issues I have done everything suggested above but it is not working.
Anyone has any idea what to do...

**Comment by AllenConway** [comment]
I ran into this problem beginning yesterday, and due to this thread being of recent I assumed it was with some versioning changes as several have mentioned above. I had the **exact** same issues, however, I hadn't updated any TS or Jasmine Types packages recently. Mine was an issue with npm locally, so I ran the following to get things sorted and my errors went away:

`npm cache verify `

**Comment by burtek** [comment]
@jeffskelton3 It wasn't me who worked on this change, nor did I publish it. I only found a possible reason. I have also nothing to do with this package itself. Those questions and notes should be addressed at the person who introduced this change, as well as DefinitelyTyped maintainers.

That being said, I totally agree with everything that has been said in this thread. It's just neither my fault, nor my responsibility.

**Comment by jeffskelton3** [comment]
@burtek apologies for directing the question at the wrong person (I must have read wrong that you were a contributor to this code base doh!). Appreciate your agreement with my sentiment and you helping everyone track down the cause of this issue.

**Comment by burtek** [comment]
@jeffskelton3 no worries

**Comment by carrotagileit** [comment]
I have the same problem two days ago. Nothing changed on my project package.json, suddenly, it fails to package with the error.

 Property 'toContainEqual' does not exist on type 'ArrayLikeMatchers
 Property 'toContainEqual' does not exist on type 'ArrayLikeMatchers

googled for two days, then come here, but still not resolved.

**Comment by skopekreep** [comment]
As another reference point, NativeScript currently targets TypeScript ~2.7.2.  Setting up a project using the NativeScript-CLI defaults to Jasmine as the default testing framework.  So just another vote to ensure that minor version updates don't also require updates to other packages.  Thanks!

**Comment by mariohmol** [comment]
I had this issue just in travis enviroment and changin to 2.5.38 worked!

https://travis-ci.org/mariohmol/ng-gantt/builds/459888259

**Comment by victorwealth** [comment]
Had same issue when running "ng test". Went to node_modules/@types/jasmine/index.d.ts.
On line 11 it says "// TypeScript Version: 2.8"

So I
C:\my-project-directory> npm install typescript@2.8
and that fixed the issue.

**Comment by maximelafarie** [comment]
I'm also running into the same errors as above. Here's the CI output: 

It's working well locally (as some above message mentions) but on GitLab CI, it's definitely broken... 🤕 

```
06 12 2018 15:34:42.681:ERROR [karma]: Error: node_modules/@types/jasmine/index.d.ts(138,47): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(138,90): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(138,104): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(138,112): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,113): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,121): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(138,147): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(138,162): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(138,163): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,164): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,165): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,179): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,183): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,208): error TS1005: '{' expected.
node_modules/@types/jasmine/index.d.ts(138,217): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,222): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,227): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,228): error TS1109: Expression expected.
node_modules/@types/jasmine/index.d.ts(138,230): error TS1005: ')' expected.

    at Compiler.compiler.plugin (/var/www/cadi-front/node_modules/@angular/cli/plugins/karma-webpack-throw-error.js:10:23)
    at Compiler.applyPlugins (/var/www/cadi-front/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/var/www/cadi-front/node_modules/webpack/lib/Compiler.js:105:17)
    at onCompiled (/var/www/cadi-front/node_modules/webpack/lib/Compiler.js:55:18)
    at applyPluginsAsync.err (/var/www/cadi-front/node_modules/webpack/lib/Compiler.js:510:14)
    at next (/var/www/cadi-front/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/var/www/cadi-front/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/var/www/cadi-front/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/var/www/cadi-front/node_modules/webpack/lib/Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (/var/www/cadi-front/node_modules/tapable/lib/Tapable.js:195:46)
    at applyPluginsAsync.err (/var/www/cadi-front/node_modules/webpack/lib/Compilation.js:677:19)
    at Compilation.applyPluginsAsyncSeries (/var/www/cadi-front/node_modules/tapable/lib/Tapable.js:195:46)
    at applyPluginsAsync.err (/var/www/cadi-front/node_modules/webpack/lib/Compilation.js:668:11)
    at Compilation.applyPluginsAsyncSeries (/var/www/cadi-front/node_modules/tapable/lib/Tapable.js:195:46)
    at applyPluginsAsync.err (/var/www/cadi-front/node_modules/webpack/lib/Compilation.js:663:10)
    at Compilation.applyPluginsAsyncSeries (/var/www/cadi-front/node_modules/tapable/lib/Tapable.js:195:46)
(node:88) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

**Comment by kingvagabond** [comment]
> "@types/jasmine": "2.8.6" & "typescript": "2.7.2" worked.
> The problem is "@types/jasmine": "~2.8.6" - > it updates to 2.8.11 incompatible with typescript to 2.7.2(require 3.+)

No... @angular/compiler-cli@5.2.11 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencies yourself.

Cannot have typescript higher than 2.7...

> "@types/jasmine": "2.8.6" & "typescript": "2.7.2" worked.
> The problem is "@types/jasmine": "~2.8.6" - > it updates to 2.8.11 incompatible with typescript to 2.7.2(require 3.+)

**Comment by jayvdb** [comment]
I needed to pin to 2.8.9 to be usable with typescript 2.6.x, which is needed for my angular 5 project

**Comment by kuroky360** [comment]
> @vnazarchukmob is it possible you have typescript installed both globally and locally and one of them is below 2.8?
> 
> @mowgliLab as I mentioned above, `@types/jasmine` is for TS 2.8+, while you're still using TS 2.7.x. Upgrade `typescript` to at least `2.8.0`.

LGTM~

**Comment by dmitryshimkin** [comment]
The version 2.8.8 works fine with TS@2.7.2, but 2.8.12 doesn't.

I am wondering how come a patch version can introduce such a breaking change 😞

**Comment by evscott** [comment]
I'm encountering this issue with a brand new Angular app using "@types/jasmine": "~2.8.6" and "typescript": "^2.8.4". Has anyone resolved this yet?

**Comment by wluijk** [comment]
Is there still no solution? It is not working as downloaded

**Comment by wluijk** [comment]
I found out all errors are gone when checking the project with this error out on Mac and running Yarn as the package manager

**Comment by byennen** [comment]
@wluijk  add

```json
{
  "typeRoots": [
    "./node_modules/@types"
  ],
  "types": ["node"]
}
```

In your `compilerOptions` and be sure to have `@types/node` installed

**Comment by RobbieClarken** [comment]
It seems to have been introduced in `@types/jasmine` version 2.8.10. Pinning to 2.8.9 fixes the problem.

**Comment by brunoribeiro-beta** [comment]
> As a side note, upgrading these types to _require_ TS 2.8+ is not a _minor_ release, this has broken many projects which now need to pin to an older types/jasmine version.
> This was a major breaking change and should of been a new major version number 😢
> 
> Pinning to `2.8.3` and leaving TS on a project that couldn't go beyond 2.5.3 worked.

Worked like a charm! Thanks a bunch friend

**Comment by alfazjikani** [comment]
> As a side note, upgrading these types to _require_ TS 2.8+ is not a _minor_ release, this has broken many projects which now need to pin to an older types/jasmine version.
> This was a major breaking change and should of been a new major version number cry
> 
> Pinning to `2.8.3` and leaving TS on a project that couldn't go beyond 2.5.3 worked.

I had entry "@types/jasmine": "~2.8.3" in package json and it was throwing an error.

I removed tilt and made it "@types/jasmine": "2.8.3" and it worked.

Note: "~2.8.3" was being updated to 2.8.11.

**Comment by mieszczans** [comment]
> I needed to pin to 2.8.9 to be usable with typescript 2.6.x, which is needed for my angular 5 project

Yes it works, but now I have warning in my console that:

> angular/compiler-cli@5.2.11 requires typescript@'>=2.4.2 <2.5.0' but 2.6.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

**Comment by jayvdb** [comment]
@mieszczans , I found typescript 2.6 was fairly stable with our angular 5 app, so we ignored that warning.  If it causes problems for you, pin the `@types/jasmine` to `2.8.4` as mentioned at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30310#issuecomment-444916003

Really, this should be reverted, as a crass violation of SemVer.

**Comment by hssa-saslanka** [comment]
Hi All,

You have just change typescript@2.8.4 and @types/jasmine@2.8.3

Like 

1. npm install typescript/2.8.4 --save-dev
2. npm install @types/jasmine@2.8.3 --save-dev

It's working 100%.

Thanks,

**Comment by iAbhinav** [comment]
Jasmine 2.8.9 along with typescript 2.80 working for me

**Comment by gaston536** [comment]
The answer makes sense https://laravel-notification-pro.github.io/-RlqahISpne3pAGSAQLER9qAbaQz3nE6YBvBrMqThkwF_aDz_n0j-FZoy9794TxIOBbtHThb2DnK/
