### ISSUE TITLE
@types/lodash@4.14.187 compilation issue

### ISSUE THREAD

**Issue by LeVraiSylvain** [DefinitelyTyped/DefinitelyTyped#63022]
Can't compile with version 4.14.187

It works well with 4.14.186

Environment
- node v14.18.1
- tsconfig : in attachment

![image](https://user-images.githubusercontent.com/25437282/199261700-f974942e-585c-46ab-adea-cee75b32fc2b.png)

**Comment by danielle-illing-ck** [comment]
In the same boat here with a service of ours. Thanks for posting!

**Comment by Lluran** [comment]
I've had the same issue - as a temporary workaround add

 `"@types/lodash": "4.14.186"`

 to the devDependencies section of your package.json file

**Comment by Polinak87** [comment]
I add section to package.json:
  "overrides": {
    "@types/lodash": "4.14.186"
  }
  
  It helps to me. Node 16.14.02

**Comment by lizheming** [comment]
This is because #62968 use Template Literal Type to definite the type of `_.get()` which is not support below Typescript < 4.1. We have discuss the resolve method in the pull request, and will fix or revert it asap. For now you can upgrade your Typescript version or you can override `@type/lodash` to old version.

**Comment by jasonChen1982** [comment]
same issue +1

**Comment by PrabuddhaAlahakoon** [comment]
same issue +1

**Comment by tushar33** [comment]
same issue +1

**Comment by Adam-Langley** [comment]
I've tried both solutions from @Lluran and @Polinak87 without any luck.
Is there something I need to do to my yarn.lock to get these solutions to work?

**Comment by Lluran** [comment]
> I've tried both solutions from @Lluran and @Polinak87 without any luck.
> Is there something I need to do to my yarn.lock to get these solutions to work?

Can you try deleting your lock file and your node modules folder and then re-running yarn (with either of the suggested solutions implemented in the package.json)

**Comment by Adam-Langley** [comment]
I've figured it out.
Turns out "overrides" doesn't work for yarn - if you're using yarn, the modification to package.json is

```
"resolutions": {
    "@types/lodash": "4.14.186"
}
```

Now my build is green again.
Thanks

**Comment by lizheming** [comment]
Latest update: we have create a new pull request to fix it #63025

**Comment by Raydir** [comment]
Same problem using Testcafe with TypeScipt (includes lodash).

**Comment by kachkaev** [comment]
@LeVraiSylvain which TypeScript version you are using?

**Comment by atsikov** [comment]
I merged https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63025 that should use previous version of definitions for TS <= 4.1, `4.14.188` should be published soon

**Comment by ntucker** [comment]
Seems like this same issue reappeared in [4.14.194](https://renovatebot.com/diffs/npm/@types%2flodash/4.14.192/4.14.194)

**Comment by SuperITMan** [comment]
The issue appears also with the version 4.14.193

**Comment by atsikov** [comment]
With TypeScript v5 released, everything below 4.2 is considered unsupported by DefinitelyTyped, and it seems a `<=4.1`  fallback that I added to `4.14.188` was removed (for good if you ask me) because of failing compilation instead of being updated to be a fallback for TS versions <=4.2.

Minimal supported TS v4.3 is already two minor versions into string template literals support, lack of which causes this compilation issue. I'd say, it's unlikely a support for older versions will be restored and maintained.

Two solutions here are either to update typescript to a version that support string template literals (>= 4.1) or to lock `@types/lodash` resolution to either `<=4.14.186` or `4.14.188`

**Comment by flavian-ioan** [comment]
Hello, same issue since 17 April. 
"typescript": "4.0.8",
"@types/lodash": "^4.14.186",
I changed the version today to 4.14.186 from 4.14.194. but still fails.

**Comment by MircoEnnova** [comment]
> Hello, same issue since 17 April. "typescript": "4.0.8", "@types/lodash": "^4.14.186", I changed the version today to 4.14.186 from 4.14.194. but still fails.

Hi, i temporarily solved the problem adding "@types/lodash": "4.14.192" in dev dependencies and overriding third dependencies using overrides in package.json as stated in some comments above. Hope it helps
"overrides": {
    "@types/lodash": "4.14.192"
},

**Comment by Indhu4399** [comment]
> > Hello, same issue since 17 April. "typescript": "4.0.8", "@types/lodash": "^4.14.186", I changed the version today to 4.14.186 from 4.14.194. but still fails.
> 
> Hi, i temporarily solved the problem adding "@types/lodash": "4.14.192" in dev dependencies and overriding third dependencies using overrides in package.json as stated in some comments above. Hope it helps "overrides": { "@types/lodash": "4.14.192" },

Have tried this not working. Which version of typescript you are using?

**Comment by MircoEnnova** [comment]
> > > Hello, same issue since 17 April. "typescript": "4.0.8", "@types/lodash": "^4.14.186", I changed the version today to 4.14.186 from 4.14.194. but still fails.
> > 
> > 
> > Hi, i temporarily solved the problem adding "@types/lodash": "4.14.192" in dev dependencies and overriding third dependencies using overrides in package.json as stated in some comments above. Hope it helps "overrides": { "@types/lodash": "4.14.192" },
> 
> Have tried this. it's not working. Which version of typescript you are using?

I am using "typescript": "~4.0.2" as part of an angular 10 project

**Comment by qtigerq** [comment]
My experience:

"devDependencies": {
    "@types/lodash": "^4.14.167",
    "typescript": "~4.0.2",
}

and i change to:

"devDependencies": {
    "@types/lodash": "4.14.186",
    "typescript": "~4.0.2",
}

This work for me.
Thanks for all.

**Comment by cetins32** [comment]
we still get same the error. @types/lodash/common/object.d.ts:2051:54 - error TS1005: ';' expected.
Can you help us please?
Node 14.16.0, npm 6.14.11
Yarn version :  1.22.18

package.json file 
    "dependencies": {
        "lodash": "^4.17.21",
        "lodash-es": "^4.17.21",
}

    "devDependencies": {
        "@types/lodash": "^4.14.186",
        "@types/lodash-es": "^4.17.7",
        "typescript": "~4.0.2",
}

**Comment by wellwelwel** [comment]
Just by importing the `lodash`, I got this:

```sh
node_modules/@types/lodash/common/common.d.ts:194:15 - error TS2589: Type instantiation is excessively deep and possibly infinite.

194     interface Object<T> extends LoDashImplicitWrapper<T> {
                  ~~~~~~

node_modules/@types/lodash/common/common.d.ts:206:15 - error TS2430: Interface 'ObjectChain<T>' incorrectly extends interface 'LoDashExplicitWrapper<T>'.
  The types returned by 'entries().pop()' are incompatible between these types.
    Type 'CollectionChain<string | T[keyof T]>' is missing the following properties from type 'ObjectChain<[string, any]>': assign, assignIn, assignInWith, assignWith, and 11 more.

206     interface ObjectChain<T> extends LoDashExplicitWrapper<T> {
                  ~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@types/lodash/common/common.d.ts:194
```

<hr />

### Reproducing this error

- package.json
```json
{
  "dependencies": {
    "lodash": "^4.17.21"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.195",
    "typescript": "^5.1.3"
  }
}
```

- tsconfig.json
```json
{
  "compilerOptions": {
    "esModuleInterop": true
  }
}
```

- index.ts
```ts
import lodash from 'lodash';
```

**Then:**
```sh
npx tsc
```

**Comment by CharlesSAUVAT** [comment]
same problem +1

**Comment by flavian-ioan** [comment]
Hey, guys so what helped me was: 1. i removed all the     "@types/lodash" library and re-added it in the devDependencies secion of the package.json with the version : "4.14.186", Pay attention to have it without the ^. It is important. I think you can do it like this npm install --save-dev --save-exact @types/lodash@4.14.186. 2. I also added the tag "overrides": {
    "@types/lodash": "4.14.186"} in the package.json. To be checked but i think the last step is not mandatory. But again very important is to have the exact version, without the ^.

**Comment by gavrielzarka** [comment]
I faces the same challenge and I tried @flavian-ioan approach with no luck.
Here is my package.json file: 

```
{
  "name": "typescript",
  "version": "1.0.0",
  "main": "app.js",
  "license": "MIT",
  "devDependencies": {
    "@types/lodash": "4.14.186",
    "typescript": "5.1.3"
  },
  "overrides": {
    "@types/lodash": "4.14.186"
  }
}
```

**Comment by adccb** [comment]
still having this error! example repo here: https://github.com/adccb/tcli/tree/types/lodash

let me know if you need any more info, but here's everything i thought might be relevant:

# error text
```
> tcli@1.0.0 build
> tsc --outDir dist/ src/index.ts

node_modules/@types/lodash/common/common.d.ts:194:15 - error TS2589: Type instantiation is excessively deep and possibly infinite.

194     interface Object<T> extends LoDashImplicitWrapper<T> {
                  ~~~~~~

node_modules/@types/lodash/common/common.d.ts:206:15 - error TS2430: Interface 'ObjectChain<T>' incorrectly extends interface 'LoDashExplicitWrapper<T>'.
  The types returned by 'entries().pop()' are incompatible between these types.
    Type 'CollectionChain<string | T[keyof T]>' is missing the following properties from type 'ObjectChain<[string, any]>': assign, assignIn, assignInWith, assignWith, and 11 more.

206     interface ObjectChain<T> extends LoDashExplicitWrapper<T> {
                  ~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@types/lodash/common/common.d.ts:194
```

<img width="790" alt="Screen Shot 2023-06-23 at 3 50 55 PM" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/13964123/2d1a5dc3-6743-4fcb-8a83-fff653fef3e7">


# version numbers
```
typescript@5.1.3
@types/lodash@4.14.186
lodash@4.17.21
node@16.20.0
```

<img width="831" alt="Screen Shot 2023-06-23 at 3 48 48 PM" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/13964123/1f7bbda6-57ba-4202-a6bd-b8592aad5df5">
<img width="1079" alt="Screen Shot 2023-06-23 at 3 49 25 PM" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/13964123/8e32dd6e-abd3-4125-b589-e8d615665939">
<img width="253" alt="Screen Shot 2023-06-23 at 3 52 02 PM" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/13964123/06d1c7d1-fd60-4e28-a28a-818fddd7da07">

**Comment by adccb** [comment]
it's worth mentioning that on the main branch of my repo above, everything compiles fine. the only diff is removing `@types/lodash`.

<img width="316" alt="Screen Shot 2023-06-23 at 4 00 46 PM" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/13964123/1592e002-9ddc-4f53-8a09-16de7e03e9bb">
<img width="2004" alt="Screen Shot 2023-06-23 at 4 04 11 PM" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/13964123/ea8e37e6-c87c-4efb-8450-50e3185093a4">

**Comment by vhnam** [comment]
Our issue will be fixed in the next version. I tried to adjust the code in `node_module` following this guide in issue [#54542](https://github.com/microsoft/TypeScript/issues/54542#issuecomment-1579175458), and it can build normally.

Seeing lines **194** and **206**. 

<img width="802" alt="Screenshot 2023-06-25 at 15 52 43" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/7885874/56003028-4001-4eca-ad70-e55d8e7b9ba9">

Or we can workaround by putting `"skipLibCheck": true` into `tsconfig.json` when waiting for the patch.

<img width="494" alt="Screenshot 2023-06-25 at 15 57 59" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/7885874/c1cfc947-0c5b-4cb0-8e86-2a3b1e900f1b">

On my end, I still use `TypeScript v5.0.4`, and `@types/lodash v4.14.195`.

**Comment by gavrielzarka** [comment]
Thanks @vhnam,
I configured the `Typescript` and `@types/lodash` versions as yours and now all works just fine.

**Comment by chenxiaosen** [comment]
Thanks @vhnam , build works

**Comment by alper** [comment]
What's the deal here? Why are there lodash types 4.14 for lodash 4.17?

**Comment by davidwwu** [comment]
This suddenly happened to our project for some reason. And I tried to update `@types/lodash` to v4.17.x but this issue still happens.

Node: 16.20.2
lodash: 4.17.21
@types/lodash: 4.17.x

```
Error: node_modules/@types/lodash/common/common.d.ts:262:65 - error TS1005: '?' expected.

262     type StringToNumber<T> = T extends `${infer N extends number}` ? N : never;
                                                                    ~


Error: node_modules/@types/lodash/common/object.d.ts:1026:46 - error TS1005: '?' expected.

1026         : K extends `${infer N extends number}` ? T[N]
                                                  ~


Error: node_modules/@types/lodash/common/object.d.ts:1026:51 - error TS2536: Type 'N' cannot be used to index type 'T'.

1026         : K extends `${infer N extends number}` ? T[N]
                                                       ~~~~


Error: node_modules/@types/lodash/common/object.d.ts:1031:46 - error TS1005: '?' expected.

1031         : K extends `${infer N extends number}` ? T[N]
                                                  ~


Error: node_modules/@types/lodash/common/object.d.ts:1031:51 - error TS2536: Type 'N' cannot be used to index type 'T'.

1031         : K extends `${infer N extends number}` ? T[N]
                                                       ~~~~


Error: node_modules/@types/lodash/common/object.d.ts:1041:46 - error TS1005: '?' expected.

1041         : K extends `${infer N extends number}`
                  
```
